.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "RAPT" "8" "April 2020" "apparmor-profile-everything" "apparmor-profile-everything Manual"
.SH "NAME"
\fBrapt\fR \- Restricted APT
.P
.SH "SYNOPSIS"
\fBrapt\fR [options]
.SH "DESCRIPTION"
TODO
.SH "WWW"
https://www\.whonix\.org/wiki/rapt
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
