#!/bin/bash

if [ -f /etc/default/networking ]; then
  . /etc/default/networking
fi

while :
do
      case $1 in
      up)
         /sbin/ifup -a --read-environment
         break
         ;;
      down)
         /sbin/ifdown -a --read-environment --exclude=lo
         break
         ;;
      *)
         break
         ;;
      esac
done
