#!/bin/bash

## Copyright (C) 2012 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

while :
do
      case $1 in
      up)
         /sbin/ifup -a --read-environment
         break
         ;;
      down)
         /sbin/ifdown -a --read-environment --exclude=lo
         break
         ;;
      *)
         break
         ;;
      esac
done
