#!/bin/sh

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

## required?
# GRUB_DEVICE="/dev/disk/by-uuid/${GRUB_DEVICE_UUID}"
# unset GRUB_DEVICE_UUID

GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX single superroot"
GRUB_DISTRIBUTOR="Recovery PERSISTENT mode SUPERADMIN (Be very cautious!)"

export \
   GRUB_DEVICE \
   GRUB_CMDLINE_LINUX \
   GRUB_DISTRIBUTOR \
   GRUB_DISABLE_RECOVERY \
   GRUB_DISABLE_SUBMENU

if test -x /etc/grub.d/10_linux ; then
	/etc/grub.d/10_linux
fi
